#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16g,walltime=36:00:00
#PBS -N roi2roitrack
#PBS -V

#set -e
#set -x

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

#TODO - if user specify their own wm_mask, skip this
if [ ! -f aparc+aseg.nii.gz ]; then
    singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./create_wm_mask.sh
fi

echo "converting dwi with fsl grad to mrtrix .mif and bgrad"
dtiinit=`jq -r '.dtiinit' config.json`
if [[ ${dtiinit} == "null" ]]; then
	DIFF=`jq -r '.dwi' config.json`
	BVALS=`jq -r '.bvals' config.json`
	BVECS=`jq -r '.bvecs' config.json`
else
	BVALS=$dtiinit/dwi_aligned*.bvals
	BVECS=$dtiinit/dwi_aligned*.bvecs
	DIFF=$dtiinit/dwi_aligned*.nii.gz
fi

if [ ! -f dwi.mif ]; then
    rm -f grad.b
    singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 mrconvert -fslgrad $BVECS $BVALS $DIFF dwi.mif --export_grad_mrtrix grad.b
fi

echo "reslicing rois"
#time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./resliceROI.sh $DIFF

echo "tracking"
time singularity exec -e docker://brainlife/mrtrix:0.2.13 ./trackROI2ROI.sh

#echo "generating wmc"
time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/classificationGenerator
if [ ! -f ./wmc/classification.mat ]; then
	echo "failed to create wmc/classification.mat"
	exit 1
fi
#mv tracts ./wmc/

echo "generating surfaces/"
time singularity exec -e docker://brainlife/pythonvtk:1.1 ./freesurfer2vtks.py aparc+aseg.nii.gz
#mv surfaces ./wmc/

echo "all done"
